### PR TITLE
updateIntl change for the 'key'

### PR DESCRIPTION
**Pull request by vmptk**
Switching locale properly

### CODE REVIEW

**Comment by jkomusin** [comment]
What problem are you looking to solve with this?

This `key` value isn't pulled from the store in the default `intl` selector, and I think the intent is that callers are welcome to provide their own selector for the IntlProvider with their own `key` implementation.

**Comment by vmptk** [comment]
without changing the key, updateIntl does not switch the locale (store used in the default Provider). IMHO key and locale should be same... as I have fall in the situation where the key was still en for example and locale was change to something else and the locale was not switched. With that change it worked perfect.

**Comment by ratson** [comment]
@vmptk Thank you for the PR, the default selector (https://github.com/ratson/react-intl-redux/blob/master/package/src/components/IntlProvider.js#L7) is already using locale as the key, and you can see the effect in https://github.com/ratson/react-intl-redux/tree/master/examples/multiple-languages.

Maybe you have hit a case I did not aware of, would you prepare a repo to demo the problem for further investigation?

**Comment by ratson** [comment]
Close as no response from author.

**Pull request closed without merging**
